grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    verbose: 2
    cv: 5

model_selection:
  model_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  model_1:
  model_2:
  